# .gitlab-ci.yml
image: docker:dind

services:
  - name: docker:dind
    command: ["--tls=false"]
    entrypoint: ["sh", "-c", "while ! docker info; do sleep 1; done"]

stages:
  - build
  - push

variables:
  # Use the GitLab Container Registry
  REGISTRY: $CI_REGISTRY
  IMAGE_TAG: $CI_COMMIT_REF_NAME
  DOCKER_TLS_CERTDIR: ""
  DOCKER_DRIVER: overlay2

before_script:
  - docker login -u ErikH -p sSuAoktqEP7Fcoz9T1ig $CI_REGISTRY

build_nginx:
  stage: build
  script:
    - echo test1
    - docker build -t $REGISTRY/erikh/praktikum-warensortierung/raspi-webserver:$IMAGE_TAG -f raspi-webserver/Dockerfile .
    - echo test2
    - docker push $REGISTRY/erikh/praktikum-warensortierung/raspi-webserver:$IMAGE_TAG
    - echo test3

build_raspi:
  stage: build
  script:
    - docker build -t $REGISTRY/erikh/praktikum-warensortierung/raspi-robot:$IMAGE_TAG -f raspi-robot/Dockerfile .
    - docker push $REGISTRY/erikh/praktikum-warensortierung/raspi-robot:$IMAGE_TAG
